// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVmO1JRU552L2OhuDi0sdRhwgleBPNO3c',
    appId: '1:81093612277:web:2701028bba2df35b4febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    authDomain: 'allnimall.firebaseapp.com',
    storageBucket: 'allnimall.appspot.com',
    measurementId: 'G-XB39WBWL38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydXSoppRjB-gdhCkIckjS0O_t9hzMgtw',
    appId: '1:81093612277:android:c203b4f38ee6059c4febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX9Kl_giqmL8K8JGZlFN6RaPLxq6g6Xp0',
    appId: '1:81093612277:ios:a5bc0499aee1dc854febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
    androidClientId:
        '81093612277-3jsns5p8689gf9anm54nc11aopnjq5at.apps.googleusercontent.com',
    iosClientId:
        '81093612277-3rl02h1qon7haddqaa6gi9kr5fi7s6u9.apps.googleusercontent.com',
    iosBundleId: 'com.allnimall.allnimallWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX9Kl_giqmL8K8JGZlFN6RaPLxq6g6Xp0',
    appId: '1:81093612277:ios:2b202dcc85acd4144febbc',
    messagingSenderId: '81093612277',
    projectId: 'allnimall',
    storageBucket: 'allnimall.appspot.com',
    androidClientId:
        '81093612277-3jsns5p8689gf9anm54nc11aopnjq5at.apps.googleusercontent.com',
    iosClientId:
        '81093612277-4nb3j18mrgrlbsifnrfmq4slf37vkt0f.apps.googleusercontent.com',
    iosBundleId: 'com.allnimall.allnimallWeb.RunnerTests',
  );
}
